name: Deploy (Dev)

on:
  push:
    branches: dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install
    - name: Run tests
      run: vendor/bin/phpunit

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        username: laravel
        host: ${{ secrets.SERVER_IP }}
        password: ${{ secrets.LARAVEL_PASSWORD }}
        script: 'cd /var/www/copilot-dev && .deploy_dev.sh'
